### ISSUE TITLE
registry metadata as API

### ISSUE THREAD

**Issue by mattiaerre** [opencomponents/oc#512]
# Description

it would be nice to have registry's metadata info exposed as an API; such as a list of available dependencies as well as plugins; @corlobepy @wmelani and myself will be more than happy to propose a PR that accommodates this need.

// cc @matteofigus @nickbalestra

**Comment by matteofigus** [comment]
I think it's a good idea.
A couple of considerations about the implementation:

1) You want the api not to conflict with any component name. We use `~` with other endpoints as that's not allowed in a component name. So perhaps it could be something like `registry.com/~/api/plugins` or `registry.com/~api/plugins/` or maybe `registry.com/~registry/plugins`? (same would apply for dependencies).
2) Dependencies and plugins are private and we possibly don't want to expose them without authentication. I think the simpler thing to do now is to have those endpoints to return JSON in case of `discovery:true` setting, and a 401 (unauthorised) if `discovery:false`.
3) When designing the dependencies endpoint, we need to be prepared to the multi-versioned dependencies that we are gonna soon support
4) I have a separate issue #489 to show the available plugins via UI. One thing I was thinking about is that atm, the registry, apart from the name of the plugin and the actual handler, knows nothing more. I was thinking about making the interface of the plugins extensible to include some docs or links to them, so that exposing the list becomes a bit more useful from a developer's perspective. Perhaps we could open a separate story for that.

**Comment by mattiaerre** [comment]
closing this issue 👋
