### ISSUE TITLE
3rd party npm packages limitation and how to use them

### ISSUE THREAD

**Issue by olteanumihai** [opencomponents/oc#918]
Hi ,

I have 2 questions:

1. Is there any restriction over any npm package which OC does not allow to consume ?
2. Which are the configurations I need to apply in order to consume a npm package after I installed it, for both local and registry environments ? 

Note: I am using oc-template-es6

**Comment by matteofigus** [comment]
Hi!

Thanks for opening an issue. 
When developing locally, you can add any dependency and devDependency to your component. If you do npm install (or use yarn etc) be sure the dependencies are in the package.json too.

When you use dependencies on the view.js, webpack should bundle the whole thing in and you shouldn't need to care about anything. When you use dependencies on the server.js, the dependencies won't be bundled in. You'll need the registry to have those dependencies whitelisted in order to, after publish, be sure your component can be executed properly.
Here is how to do it on the registry: https://github.com/opencomponents/oc/wiki/Registry#registry-configuration
´´´js
...
dependencies: ['lodash', 'underscore'],
...
´´´
(they also need to be installed in the node app where the registry is running).

Now a little advanced note...we are changing this on the server.js soon. I think in the future, if the dependency will be declared as "devDependency" both in the server.js and view.js it will be bundled in, if not it won't. But this is still a WIP.

Does this answer your question?

**Comment by olteanumihai** [comment]
This answers to my question. Thanks !
